driver:
  name: vagrant

provisioner:
  name: chef_zero
  
platforms:
  - name: windows-2012r2
    driver_config:
      box: dhoer/windows-2012r2
      vm_hostname: winrm-test

suites:
  - name: default
    run_list:
      - recipe[winrm::default]
