name             'winrm'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs and configures WinRM'
supports         'windows'
source_url       'https://github.com/sous-chefs/winrm'
issues_url       'https://github.com/sous-chefs/winrm/issues'
chef_version     '>= 15.4'
version          '4.0.3'
