name             'winrm'
maintainer       'Webtrends, Inc.'
maintainer_email 'Peter Crossley <peter.crossley@webtrends.com>'
license          'Apache 2.0'
description      'Installs and configures WinRM'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '1.0.0'
supports         'windows'
depends          'windows'
depends          'powershell'
